server:
  port: 8888
spring:
  application:
    name: hystrix-dashboard-turbine
turbine:
  app-config: abcmsc-consumer-depart,node02  # 配置Eureka中的serviceId列表，表明监控哪些服务
  aggregator:
    cluster-config: default #指定聚合哪些集群，多个使用”,”分割，默认为default。可使用http://.../turbine.stream?cluster={clusterConfig之一}访问
  cluster-name-expression: new String("default")
  combine-host-port: true
eureka:
  client:
    service-url:
      defaultZone:  http://127.0.0.1:8100/eureka,http://127.0.0.1:8200/eureka,http://127.0.0.1:8300/eureka
