server:
  port: 8081
spring:
  jpa:
    #指定spring容器自动启动时是否生成表，默认false
    generate-ddl: true
    #在控制台打印sql语句.默认false
    show-sql: true
    #指定应用重启后不更新表内容
    hibernate:
      ddl-auto: none
  #数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///test?useUnicode=true&amp;characterEncoding=utf-8
    username: root
    password: hongzong
  devtools:
    restart:
      #设置热部署生效
      enabled: true
      #排除静态资源
      exclude: static
    #日志配置
    #指定微服务名称
  application:
    name: abcmsc-provider-depart
logging:
  pattern:
    console: level-%level %msg%n
  level:
    root: info
    org.hibernate: info
    #在show-sql为true时显示SQL中的动态参数
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    #在show-sql为true时显示查询结果
    org.hibernate.hql.internal.ast.exec.BasicExecutor: trace
eureka:
  client:
    service-url:
      #指定当前client 需要连接的eureka server地址
      defaultZone:  http://127.0.0.1:8100/eureka,http://127.0.0.1:8200/eureka,http://127.0.0.1:8300/eureka
#  instance:
#    instance-id: abcmsc-provider-8081

info:
  auth: Reythor
  app.name: abcmsc
  company.name: www.kaikeba.com
  #region与zone一对多1:n
  #zone与eureka的关系1:n
#eureka:
#  client:
#    #指定区域名称
#    region: xxx
#    #指定区域中包含的地带zone
#    availability-zones:
#      xxx: kkb1,kkb2
#   #指定各地带zone所包含的eureka server地址
#    service-url:
#      kkb1: http://localhost:8000/eureka
#      kkb2: http://localhost:8000/eureka
#      #指定要连接的注册中心所在区域
#    fetch-remote-regions-registry:  xxx

    #注入Eureka server依赖
    #指定要注册的Eureka server地址，指定自己的微服务名称
    #在javaConfig里面设置restTemplate，为负载均很@LoadBalance
    #修改处理器将主机名：端口，改成，提供微服务名称

management:
  #开启所有监控终端
  endpoints:
    web:
      exposure:
        include: "*"
        #开启shoudown 监控终端
  endpoint:
    shutdown:
      enabled: true
#post  http://localhost:8081/actuator/shutdown   下架服务
#post http://localhost:8081/actuator/service-registry 下线服务  {
      #  "status":"DOWN"}